# Example Nav2 Parameters for a Simulated Humanoid Robot

# This is a simplified version of a Nav2 parameters file.
# A real configuration file would be much more extensive.

# General Parameters
use_sim_time: True

# AMCL - Localization Node
amcl:
  ros__parameters:
    use_sim_time: True
    odom_frame_id: "odom"
    base_frame_id: "base_link"
    global_frame_id: "map"
    # Provide a smaller particle count for faster simulation
    min_particles: 500
    max_particles: 2000
    # Update rates
    update_min_d: 0.1
    update_min_a: 0.2
    # Laser model parameters
    laser_max_beams: 60
    laser_z_hit: 0.95
    laser_z_rand: 0.05

# Global Planner
planner_server:
  ros__parameters:
    use_sim_time: True
    # Using the default NavFn planner
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 0.5

# Local Planner / Controller
controller_server:
  ros__parameters:
    use_sim_time: True
    # Using the default DWB controller
    controller_plugins: ["FollowPath"]
    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      # Robot footprint for collision checking
      footprint: "[ [0.1, 0.075], [0.1, -0.075], [-0.1, -0.075], [-0.1, 0.075] ]"
      # Velocity limits
      max_vel_x: 0.25
      min_vel_x: 0.0
      max_vel_y: 0.0
      min_vel_y: 0.0
      max_vel_theta: 0.5
      min_vel_theta: -0.5
      acc_lim_x: 1.0
      acc_lim_theta: 1.5

# Global and Local Costmaps
global_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_rate: 5.0
  publish_rate: 5.0
  # Using static map layer and inflation layer
  plugins: ["static_layer", "inflation_layer"]
  static_layer:
    plugin: "nav2_costmap_2d::StaticLayer"
    map_subscribe_transient_local: True
  inflation_layer:
    plugin: "nav2_costmap_2d::InflationLayer"
    cost_scaling_factor: 3.0
    inflation_radius: 0.35

local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_rate: 10.0
  publish_rate: 10.0
  width: 3
  height: 3
  resolution: 0.05
  # Using voxel layer for 3D obstacles from depth camera and inflation layer
  plugins: ["voxel_layer", "inflation_layer"]
  voxel_layer:
    plugin: "nav2_costmap_2d::VoxelLayer"
    enabled: True
    publish_voxel_map: True
    origin_z: 0.0
    z_resolution: 0.05
    z_voxels: 16
    max_obstacle_height: 2.0
    mark_threshold: 0
    observation_sources: "depth_camera"
    depth_camera:
      topic: /robot/camera/depth/image_raw
      max_obstacle_height: 2.0
      min_obstacle_height: 0.0
      sensor_frame: head_camera_link
      data_type: "Image"
  inflation_layer:
    plugin: "nav2_costmap_2d::InflationLayer"
    cost_scaling_factor: 5.0
    inflation_radius: 0.25
